### PR TITLE
feat: add convergence info in results

### PR DESCRIPTION
**Pull request by qiangyicheng**

### CODE REVIEW

**Comment by david-zwicker** [comment]
I made some minor suggestions – let's discuss them when we find the time.

**Comment by qiangyicheng** [comment]
Sure! I actually like the changes quite a lot. It keeps the `Finder` class decoupled.

**Comment by david-zwicker** [comment]
That was the idea :)

**Comment by david-zwicker** [comment]
Can we merge this PR or are there still open problems?

**Pull request merged**
