### PR TITLE
Changed the return type from a tuple to a separate class

### PR DESCRIPTION
**Pull request by david-zwicker**
I hope this avoids errors (so one does not need to remember whether the phase volume was the first or second entry). The class also allows to add convenience methods and some checks if we want this later.

### CODE REVIEW

**Comment by david-zwicker** [comment]
I currently base the new `Phases` class on the tuple approach that we had so far, so the class works as a drop-in replacement. However, we could also decide to get rid of the tuples completely (particularly in the examples) and base everything on class access.

**Comment by david-zwicker** [comment]
We should also discuss whether we should call the fields `Js` and `phis` or rather `volumes` and `fractions` or something similar.

**Comment by qiangyicheng** [comment]
I like this! For exposing the clustering threshold, can we let the Phases class also hold the original phis and Js as private members? Then we can re-cluster the phases when needed.

**Comment by david-zwicker** [comment]
Let's discuss this in person some time this week!

**Pull request merged**
