### PR TITLE
Added `get_uniform_random_composition` function

### PR DESCRIPTION
**Pull request by david-zwicker**
Additionall ran `ruff check --fix` to fix some style issues

### CODE REVIEW

**Comment by david-zwicker** [comment]
Looks like I messed up the branch where I did the edits. These changes do not seem to be based on `main`. Do you know how to change this?

**Comment by qiangyicheng** [comment]
I thinks it's fine. After we merge the `dev_paper` branch, we can merge main into this branch. Currently `dev_paper` branch is just ahead of `main`.

**Comment by david-zwicker** [comment]
Good – I should still be a bit more careful with this

**Comment by david-zwicker** [comment]
Ok, `rebase` did not do what I thought it would do... At least this branch now does not have any conflicts with the main branch anymore...

**Pull request merged**
